# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

[tools]
rojo = "rojo-rbx/rojo@7.7.0"
wally = "UpliftGames/wally@0.3.2"
selene = "Kampfkarren/selene@0.31.0"
stylua = "JohnnyMorganz/stylua@2.5.2"